name: Pre-merge Build and Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  environment: "build"
  awsRegion: "eu-west-2"
  eventProcessorDirectory: "event-processing"
  auditDirectory: "audit"
  analysisDirectory: "analysis"

jobs:
  run_event_processor_tests_and_validation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ${{ env.eventProcessorDirectory }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v1
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_VALIDATE_ROLE_ARN_EVENT_PROCESSING }}
          aws-region: ${{ env.awsRegion }}
      - name: Use Node.js 14
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.x'
      - name: Install Lambda Dependencies
        working-directory: ${{ env.eventProcessorDirectory }}/lambda
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Test Lambdas
        working-directory: ${{ env.eventProcessorDirectory }}/lambda
        run: yarn test
      - name: SAM Validate
        run: |
          sam validate --template-file event-processing-template.yml --config-env ${{ env.environment }}

  run_audit_validation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ${{ env.auditDirectory }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v1
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_VALIDATE_ROLE_ARN_AUDIT }}
          aws-region: ${{ env.awsRegion }}
      - name: Use Node.js 14
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.x'
      - name: Install Lambda Dependencies
        working-directory: ${{ env.auditDirectory }}/lambda
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Test Lambdas
        working-directory: ${{ env.auditDirectory }}/lambda
        run: yarn test
      - name: SAM Validate
        run: |
          sam validate --template-file audit-template.yml --config-env ${{ env.environment }}

  run_analysis_validation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ${{ env.analysisDirectory }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v1
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_VALIDATE_ROLE_ARN_AUDIT }}
          aws-region: ${{ env.awsRegion }}
      - name: SAM Validate
        run: |
          sam validate --template-file analysis-template.yml --config-env ${{ env.environment }}